apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-username: "cm9vdA=="
  mysql-password: "cm9vdA=="
  mysql-root-password: "cm9vdA=="
  mysql-database: "c3R1ZGVudA=="
