apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage size as per your requirements
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-pv-storage
  hostPath:
    path: /var/lib/mysql # Replace with the actual path on your host machine where you want to store MySQL data
